[build]
  # Directory to publish (relative to root of your repo)
  publish = "dist"
  # Default build command
  command = "npm run build"

[build.environment]
  # Set Node version
  NODE_VERSION = "18"

# Redirects for single-page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
